
title: 温一壶月光下酒 #Your awesome title
email: #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: # the subpath of the site
url: https://nevercr.github.io# the base hostname & protocol for your site

permalink: /:title/
paginate_path: /page:num/
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname

user:
  name: NEVER
  pic: /tx.png
  picAlt: "bobolook"
  job: Love In Mind
  about: /about
  link: /link
  

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
